Apps/Auth/urls.py
from django.urls import path
from Apps.Auth import views



app_name = 'Auth'

urlpatterns = [

    path('signup/', views.Signup.as_view(template_name='Auth/signup.html'), name='Signup'),
    path('confirm-signup/', views.ConfirmSignup.as_view(template_name='Auth/confirm-signup.html'), name='Confirm-Signup'),

    path('login/', views.Login.as_view(template_name='Auth/login.html'), name='Login'),
    path('login-as-guest/', views.LoginAsGuest.as_view(), name='Guest-Login'),
    path('logout/', views.Logout.as_view(), name='Logout'),

    path('forget-password/', views.ForgetPassword.as_view(template_name='Auth/forget-password.html'), name='Forget-Password'),
    path('reset-password/', views.ResetPassword.as_view(template_name='Auth/reset-password.html'), name='Reset-Password'),
]

Apps/Info/urls.py
from django.urls import path
from . import views


app_name = 'Info'

urlpatterns = [

    path('feedback/', views.FeedbackView.as_view(template_name='Info/Feedback.html'), name='Feedback'),

    path('who-i-am/', views.WhoIAmView.as_view(template_name='Info/WhoIAm.html'), name='WhoIAm'),

    path('download-cv/', views.DownloadCV.as_view(), name='Download-CV'),
]

Apps/Profile/urls.py
from django.urls import path
from . import views



app_name = 'Profile'

urlpatterns = [

    path('password/', views.PasswordView.as_view(template_name='Profile/Password.html'), name='Password'),

    path('settings/', views.SettingsView.as_view(template_name='Profile/Settings.html'), name='Settings'),

    path('', views.ProfileView.as_view(template_name='Profile/Profile.html'), name='Profile'),
]

Apps/Url/urls.py
from django.urls import path, include
from . import views



app_name = 'Url'

urlpatterns = [

    path('create/', views.CreateUrlView.as_view(template_name='Url/Create.html'), name='Create'),

    path('<int:Url_id>/', views.UrlView.as_view(template_name='Url/Url.html'), name='Url'),

    path('', views.UrlsView.as_view(template_name='Url/Home.html'), name='Home'),

    path('<slug:Short_Url>/', views.RedirectUrlView.as_view(), name='Redirect'),
]

short_url/urls.py
import os
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from Apps.Info import views



urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('Apps.Auth.urls')),

    path('profile/', include('Apps.Profile.urls')),

    path('info/', include('Apps.Info.urls')),

    path('urls/', include('Apps.Url.urls')),

    path('api/', include([

        path('auth/', include('Apps.Auth.api.urls')),

        path('profile/', include('Apps.Profile.api.urls')),

        path('info/', include('Apps.Info.api.urls')),

        path('urls/', include('Apps.Url.api.urls')),
    ])),

    path('', views.HomeView.as_view(template_name='Info/Home.html'), name=''),
]


urlpatterns += static(
    settings.MEDIA_URL + 'user/',
    document_root=os.path.join(apps.get_app_config('Profile').path, 'media', 'user'),
)

Apps/Url/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _




class Url(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(_('Url Title'), max_length=100, default='')
    description = models.CharField(_('Url Description'), max_length=2000, default='')
    url = models.CharField(_('Url'), max_length=2000)
    short_url = models.CharField(_('Short Url'), max_length=100)
    is_deleted = models.BooleanField(_('Is Url Deleted'), default=False)
    created_at = models.DateTimeField(_('Url Created At'), auto_now_add=True)


    class Meta:
        indexes = [
            models.Index(fields=['short_url'], name='short_url_idx'),
            models.Index(fields=['short_url', 'is_deleted'], name='short_url_without_delete_idx')
        ]

Apps/Url/api/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework import serializers
from .serializers import UrlSerializer
from .mixins import BaseUrlAPI
from ..models import Url
from ..helper import Random




class UrlsAPI(BaseUrlAPI, ListCreateAPIView):
    throttle_scope = 'urls', '100/min'
    serializer_class = UrlSerializer

    def get_queryset(self):
        return Url.objects.filter(user=self.request.user, is_deleted=False).order_by('-id')

    def perform_create(self, serializer: serializers.ModelSerializer):
        _Count = Url.objects.count()
        serializer.save(user=self.request.user, short_url=Random.create_random_token(_Count + 1, _Count + 3))


class UrlAPI(BaseUrlAPI, RetrieveUpdateDestroyAPIView):
    throttle_scope = 'url', '100/min'
    serializer_class = UrlSerializer
    lookup_url_kwarg = 'Url_id'

    def get_queryset(self):
        return Url.objects.filter(user=self.request.user, is_deleted=False)
    
    def perform_destroy(self, instance):
        instance.is_deleted = True
        instance.save()

Apps/Url/views.py
from django.views.generic import ListView, CreateView, UpdateView, RedirectView
from django.http import Http404, HttpRequest, JsonResponse
from django.urls import reverse
from Apps.Auth.mixins import LoginRequiredMixin, SuccessMessageMixin
from Apps.Profile.mixins import ProfileMixin
from .helper import Random
from .models import Url



class UrlsView(LoginRequiredMixin, ProfileMixin, ListView):
    def get_queryset(self):
        return Url.objects.filter(user=self.request.user, is_deleted=False).order_by('-id')


class CreateUrlView(LoginRequiredMixin, ProfileMixin, SuccessMessageMixin, CreateView):

    success_flash_message_name = 'success_create_url'
    success_flash_message = 'Your Link Created Successfully'

    model = Url
    fields = ['title', 'description', 'url']

    def get_success_url(self):
        return reverse('Url:Url', kwargs={'Url_id': self.object.id})

    def form_valid(self, form):
        _Count = Url.objects.count()
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.short_url = Random.create_random_token(_Count + 1, _Count + 3)
        self.object.save()
        return super().form_valid(form)


class UrlView(LoginRequiredMixin, ProfileMixin, SuccessMessageMixin, UpdateView):

    success_flash_message_name = 'success_edit_url'
    success_flash_message = 'Your Link Edited Successfully'

    model = Url
    fields = ['title', 'description', 'url']

    def get_success_url(self):
        return reverse('Url:Url', kwargs={'Url_id': self.object.id})

    def get_object(self, queryset=None):
        self._url = Url.objects.filter(id=self.kwargs['Url_id'], user=self.request.user, is_deleted=False).first()
        if self._url is None: raise Http404('URL Not Found Or Not URL Creator')
        self._url.updated_short_url = self.request.build_absolute_uri(
            reverse('Url:Redirect', kwargs={'Short_Url': self._url.short_url})
        )
        return self._url
    
    def delete(self, request: HttpRequest, Url_id: str):
        _Url = Url.objects.filter(id=self.kwargs['Url_id'], user=self.request.user, is_deleted=False).first()
        _Url.is_deleted = True
        _Url.save()
        return JsonResponse({'Result': 'Done'})


class RedirectUrlView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        _Url = Url.objects.filter(short_url=kwargs['Short_Url'], is_deleted=False).first()
        if _Url is None: raise Http404('Link Does Not Exists')
        return _Url.url

Apps/Url/templates/Url/Create.html
{% extends 'Url/base.html' %}
{% load static %}

{% block title %} Create New Link {% endblock %}



{% block content %}

    <br /><br /><br />

    <h1 class="text-center">Create New Link</h1>

    <br /><br />

    <form method="post" id="Form">

        {% csrf_token %}

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="title">Url Title</label>
                <input type="text" class="form-control" name="title" id="title" required
                    value="{{ form.title.value|default:'' }}" placeholder="Enter Url Title Here">
                <small style="color: #dc3545;" id="title-errors">
                    {{ form.title.errors }}
                </small>
            </div>
        
        </div>

        <br />

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="long-url">Url Long Url</label>
                <input type="text" class="form-control" name="url" id="long-url" required
                    value="{{ form.url.value|default:'' }}" placeholder="Enter Long Url Here">
                <small style="color: #dc3545;" id="long-url-errors">
                    {{ form.url.errors }}
                </small>
            </div>
        
        </div>

        
        <br />

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="description">Url Description</label>
                <textarea class="form-control" id="description" name="description" required rows="4"
                    placeholder="Enter Url Description Here">{{ form.description.value|default:'' }}</textarea>
                <small style="color: #dc3545;" id="description-errors">
                    {{ form.description.errors }}
                </small>
            </div>
        
        </div>

        <br />

        <button class="btn btn-success" type="submit">Create Url</button>


      </form>
      <br /><br /><br />
{% endblock %}




{% block scripts %}
<script src="{% static 'Url/javascript/createUrl.js' %}"></script>
{% endblock %}

Apps/Url/templates/Url/Home.html
{% extends 'Url/base.html' %}

{% block title %} Urls {% endblock %}

{% block content %}
    <br />
            
    <h1 class="text-center" >Urls</h1>

    {% for url_obj in object_list %}

        <br />

        <div class="media position-relative">
            <div class="media-body">
            <h5 class="mt-0">{{ url_obj.title }}</h5>
            <p>{{ url_obj.description }}</p>
            <a href="{% url 'Url:Url' url_obj.id %}" class="btn btn-success stretched-link">Edit Link</a>
            </div>
        </div>

    {% endfor %}
    
{% endblock %}

Apps/Url/templates/Url/Url.html
{% extends 'Url/base.html' %}
{% load static %}

{% block title %} {{ form.title.value }} {% endblock %}

{% block content %}

    {% if request.flash_message.exists.success_create_url %}
        {% include 'Url/utilts/model.html' with ModelMessage=request.flash_message.success_create_url %}
    {% elif request.flash_message.exists.success_edit_url %}
        {% include 'Url/utilts/model.html' with ModelMessage=request.flash_message.success_edit_url %}
    {% endif %}

    <br /><br /><br />

    <h1 class="text-center">{{ form.title.value }}</h1>

    <form method="post" id="Form">

        {% csrf_token %}

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="title">Url Title</label>
                <input type="text" class="form-control" name="title" id="title" required
                    value="{{ form.title.value|default:'' }}" placeholder="Enter Url Title Here">
                <small style="color: #dc3545;" id="title-errors">
                    {{ form.title.errors }}
                </small>
            </div>
        
        </div>

        <br />

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="long-url">Url Long Url</label>
                <input type="text" class="form-control" name="url" id="long-url" required
                    value="{{ form.url.value|default:'' }}" placeholder="Enter Long Url Here">
                <small style="color: #dc3545;" id="long-url-errors">
                    {{ form.url.errors }}
                </small>
            </div>
        
        </div>

        <br />

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="description">Url Description</label>
                <textarea class="form-control" id="description" name="description" required rows="4"
                    placeholder="Enter Url Description Here">{{ form.description.value|default:'' }}</textarea>
                <small style="color: #dc3545;" id="description-errors">
                    {{ form.description.errors }}
                </small>
            </div>
        
        </div>

        <br />

        <div class="form-row">
        
            <div class="col-md-8 mb-3">
                <label for="short_url">Short Url</label>
                <input type="text" class="form-control" id="short-url" required
                    value="{{ object.updated_short_url }}" disabled>
            </div>
        
        </div>

        <br />

        <button class="btn btn-success" type="submit">Edit Url</button>
        
      </form>

      <br />

      <button class="btn btn-danger" id="Delete" Url="{% url 'Url:Url' object.id %}" Home="{% url '' %}">Delete Url</button>
      <br /><br /><br />

{% endblock %}




{% block scripts %}
<script src="{% static 'Url/javascript/url.js' %}"></script>
{% endblock %}

Apps/Url/templates/Url/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" href="{% static 'Url/images/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% include 'Url/navbar.html' %}

    <div class="container">

        {% block content %}{% endblock %}

    </div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <!--<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->


    
    {% block scripts %}{% endblock %}

  </body>
</html>

Apps/Url/templates/Url/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url '' %}">Url</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Url:Create' %}">Create New Link <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">

        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hello {{ request.user.get_short_name }} 
              <img src="{{ profile.avatar.url }}" width="30" height="30" class="rounded-circle">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="position: fixed; right: 10px;top: auto; left: auto;">
              <a class="dropdown-item" href="{% url '' %}">Dashboard</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'Profile:Profile' %}">Edit Profile</a>
              <a class="dropdown-item" href="{% url 'Profile:Password' %}">Change Password</a>
              <a class="dropdown-item" href="{% url 'Profile:Settings' %}">Settings</a>
              {% if request.user.is_superuser %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Dashboard</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'Auth:Login' %}">Switch Account</a>
              <a class="dropdown-item" href="{% url 'Auth:Logout' %}">Log Out</a>
            </div>
          </li>
        </ul>

      </div>
    </div>
</nav>